=== DQinYuan/fakerpp/fakerpp-core/src/main/resources/fakerpp.xsd
<!-- incomplete xsd only for test, complete xsd will be generated in compile -->
<xs:schema
        xmlns:xs='http://www.w3.org/2001/XMLSchema'
        xmlns='https://github.com/dqinyuan/fakerpp'
        targetNamespace='https://github.com/dqinyuan/fakerpp'
        elementFormDefault='qualified'>

    <xs:complexType name="tableType">
        <xs:sequence>
            <xs:element ref="joins" minOccurs="0"/>
            <xs:element ref="col-families"/>
            <xs:element ref="excludes" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:token" use="required"/>
        <xs:attribute name="ds" type="xs:string" default=""/>
        <xs:attribute name="num" type="xs:int" default="0"/>
    </xs:complexType>

    <xs:complexType name="leftjoinType">
        <xs:sequence>
            <xs:element ref="map" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="depend" type="xs:token" use="required"/>
    </xs:complexType>

    <xs:complexType name="rightjoinType">
        <xs:sequence>
            <xs:element ref="map" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="depend" type="xs:token" use="required"/>
        <xs:attribute name="random" type="xs:boolean" default="false"/>
    </xs:complexType>

    <xs:complexType name="mapType">
        <xs:simpleContent>
            <xs:extension base="xs:token">
                <xs:attribute name="from" type="xs:token" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="joinsType">
        <!-- in any order any times -->
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="leftjoin"/>
            <xs:element ref="rightjoin"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="excludesType">
        <xs:sequence>
            <xs:element name="exclude" type="xs:token" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="table" type="tableType"/>
    <xs:element name="joins" type="joinsType"/>
    <xs:element name="col-families" type="colFamiliesType"/>
    <xs:element name="excludes" type="excludesType"/>
    <xs:element name="map" type="mapType"/>
    <xs:element name="leftjoin" type="leftjoinType"/>
    <xs:element name="rightjoin" type="rightjoinType"/>


    <!-- col and cols -->
    <!-- col tag can not be empty or null -->
    <xs:simpleType name="colType">
        <xs:restriction base="xs:string">
            <!-- \S reparents all non empty char -->
            <xs:pattern value="\S+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="colsType">
        <xs:sequence>
            <xs:element name="col" type="colType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <!-- base generator type -->
    <xs:complexType name="baseGenType">
        <xs:sequence>
            <xs:element name="cols" type="colsType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <!-- options type -->
    <xs:complexType name="optionType">
        <xs:sequence>
            <xs:element name="cell"
                        type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="optionsType">
            <xs:sequence>
                <xs:element name="option" type="optionType" maxOccurs="unbounded"/>
            </xs:sequence>
    </xs:complexType>


    <!-- built in generators -->

    <xs:complexType name="builtInType">
        <xs:choice>
            <!-- str generator -->
            <xs:element name="str">
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="baseGenType">
                            <xs:attribute name="prefix" type="xs:token" default=""/>
                            <xs:attribute name="suffix" type="xs:token" default=""/>
                            <xs:attribute name="len" type="xs:integer" default="10"/>
                        </xs:extension>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
            <!-- date generator -->
            <xs:element name="date">
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="baseGenType">
                            <xs:attribute name="format" type="xs:token" default="yyyy-MM-dd"/>
                            <xs:attribute name="start" type="xs:token" default="end-60"/>
                            <xs:attribute name="end" type="xs:token" default="now"/>
                        </xs:extension>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
            <!-- date range generator -->
            <xs:element name="date-range">
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="baseGenType">
                            <xs:attribute name="format" type="xs:token" default="yyyy-MM-dd"/>
                            <xs:attribute name="start" type="xs:token" default="end-60"/>
                            <xs:attribute name="end" type="xs:token" default="now"/>
                        </xs:extension>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
            <!-- enum generator -->
            <xs:element name="enum">
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="baseGenType">
                            <xs:sequence>
                                <xs:element name="options" type="optionsType"/>
                            </xs:sequence>
                        </xs:extension>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
            <!-- const generator -->
            <xs:element name="const">
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="baseGenType">
                            <xs:sequence>
                                <xs:element name="options" type="optionsType"/>
                            </xs:sequence>
                        </xs:extension>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
            <!-- int generator -->
            <xs:element name="int">
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="baseGenType">
                            <xs:attribute name="min" type="xs:int" default="0"/>
                            <xs:attribute name="max" type="xs:int" default="100"/>
                        </xs:extension>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
        </xs:choice>
    </xs:complexType>

    <!-- faker generators -->

    <xs:complexType name="baseFakerFieldType">
        <xs:attribute name="lang" default="default"/>
    </xs:complexType>

    <xs:complexType name="nameType">
        <xs:complexContent>
            <xs:extension base="baseFakerFieldType">
                <xs:choice>
                    <xs:element type="baseGenType" name="name"/>
                    <xs:element type="baseGenType" name="name-with-middle"/>
                    <xs:element type="baseGenType" name="full-name"/>
                    <xs:element type="baseGenType" name="first-name"/>
                    <xs:element type="baseGenType" name="last-name"/>
                    <xs:element type="baseGenType" name="prefix"/>
                    <xs:element type="baseGenType" name="suffix"/>
                    <xs:element type="baseGenType" name="title"/>
                    <xs:element type="baseGenType" name="username"/>
                    <xs:element type="baseGenType" name="blood-group"/>
                </xs:choice>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="numberType">
        <xs:complexContent>
            <xs:extension base="baseFakerFieldType">
                <xs:choice>
                    <xs:element type="baseGenType" name="random-digit"/>
                    <xs:element type="baseGenType" name="random-digit-not-zero"/>
                    <xs:element name="number-between">
                        <xs:complexType>
                            <xs:complexContent>
                                <xs:extension base="baseGenType">
                                    <!-- 这如果自动生成的话考虑**多态**需要进行类型推导 -->
                                    <xs:attribute name="min" type="xs:long" use="required"/>
                                    <xs:attribute name="max" type="xs:long" use="required"/>
                                </xs:extension>
                            </xs:complexContent>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="random-number">
                        <xs:complexType>
                            <xs:complexContent>
                                <xs:extension base="baseGenType">
                                    <xs:attribute name="number-of-digits" type="xs:int" use="required"/>
                                    <xs:attribute name="strict" type="xs:boolean" use="required"/>
                                </xs:extension>
                            </xs:complexContent>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="random-double">
                        <xs:complexType>
                            <xs:complexContent>
                                <xs:extension base="baseGenType">
                                    <xs:attribute name="max-number-of-decimals" type="xs:int" use="required"/>
                                    <!--多态-->
                                    <xs:attribute name="min" type="xs:long" use="required"/>
                                    <xs:attribute name="max" type="xs:long" use="required"/>
                                </xs:extension>
                            </xs:complexContent>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="decimal-between">
                        <xs:complexType>
                            <xs:complexContent>
                                <xs:extension base="baseGenType">
                                    <xs:attribute name="min" type="xs:long" use="required"/>
                                    <xs:attribute name="max" type="xs:long" use="required"/>
                                </xs:extension>
                            </xs:complexContent>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="digits">
                        <xs:complexType>
                            <xs:complexContent>
                                <xs:extension base="baseGenType">
                                    <!-- 这里不需要required是因为多态 -->
                                    <xs:attribute name="count" type="xs:long"/>
                                </xs:extension>
                            </xs:complexContent>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <!-- register all generators -->
    <xs:group name="anyOneGenerator">
        <xs:choice>
            <!-- built-in generator -->

            <xs:element name="built-in" type="builtInType"/>

            <!-- java faker generator -->

            <xs:element name="name" type="nameType"/>
            <xs:element name="number" type="numberType"/>
        </xs:choice>
    </xs:group>

    <xs:complexType name="composesType">
        <xs:complexContent>
            <xs:extension base="baseGenType">
                <xs:sequence>
                    <xs:element name="compose" maxOccurs="unbounded">
                        <xs:complexType>
                            <!-- in any order any times -->
                            <xs:choice>
                                <xs:group ref="anyOneGenerator"/>
                            </xs:choice>
                            <xs:attribute name="weight" type="xs:int" default="1"/>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="colFamiliesType">
        <!-- in any order any times -->
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="anyOneGenerator"/>
            <xs:element name="composes" type="composesType"/>
        </xs:choice>
    </xs:complexType>
</xs:schema>

=== DQinYuan/fakerpp/fakerpp-core/src/test/resources/org.testany.fakerpp.core.parser/examples/user_shop/user_shop.xml
<?xml version="1.0" encoding="UTF-8" ?>
<table xmlns="https://github.com/dqinyuan/fakerpp"
       xsi:schemaLocation="https://github.com/dqinyuan/fakerpp
       https://raw.githubusercontent.com/dqinyuan/master/fakerpp.xsd"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       name="user_shop" ds="mysql">
    <joins>
        <rightjoin target="dt"/>
        <rightjoin target="shop"/>
        <leftjoin target="user"/>
    </joins>
    <col-families>
        <number>
            <random-double max-number-of-decimals="2" min="90" max="10000">
                <cols>
                    <col>amount</col>
                </cols>
            </random-double>
        </number>
    </col-families>
    <excludes>
        <exclude>id</exclude>
    </excludes>
</table>

=== DQinYuan/fakerpp/fakerpp-core/src/test/resources/org.testany.fakerpp.core.parser/examples/user_shop/user_detail.xml
<?xml version="1.0" encoding="UTF-8" ?>
<table xmlns="https://github.com/dqinyuan/fakerpp"
       xsi:schemaLocation="https://github.com/dqinyuan/fakerpp
       https://raw.githubusercontent.com/dqinyuan/master/fakerpp.xsd"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       name="user_detail" ds="mysql">
    <joins>
        <rightjoin target="user"/>
    </joins>
    <col-families>
        <str prefix="street_" len="3">
            <cols>
                <col>address</col>
            </cols>
        </str>
        <str len="30">
            <cols>
                <col>description</col>
            </cols>
        </str>
    </col-families>
    <excludes>
        <exclude>id</exclude>
    </excludes>
</table>

=== DQinYuan/fakerpp/fakerpp-core/src/test/resources/org.testany.fakerpp.core.parser/examples/user_shop/shop.xml
<?xml version="1.0" encoding="UTF-8" ?>
<table xmlns="https://github.com/dqinyuan/fakerpp"
       xsi:schemaLocation="https://github.com/dqinyuan/fakerpp
       https://raw.githubusercontent.com/dqinyuan/master/fakerpp.xsd"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       name="shop" num="3" virtual="true" ds="">
    <col-families>
        <str len="3" prefix="Shop_">
            <cols>
                <col>name</col>
            </cols>
        </str>
        <str len="3" prefix="Owner_">
            <cols>
                <col>owner</col>
            </cols>
        </str>
    </col-families>
</table>

=== DQinYuan/fakerpp/fakerpp-core/src/test/resources/org.testany.fakerpp.core.parser/examples/user_shop/user.xml
<?xml version="1.0" encoding="UTF-8" ?>
<table xmlns="https://github.com/dqinyuan/fakerpp"
       xsi:schemaLocation="https://github.com/dqinyuan/fakerpp
       https://raw.githubusercontent.com/dqinyuan/master/fakerpp.xsd"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       name="user" num="15" virtual="true" ds="">
    <col-families>
        <name>
            <full-name>
                <cols>
                    <col>name</col>
                </cols>
            </full-name>
        </name>
        <enum>
            <cols>
                <col>sex</col>
            </cols>
            <options>
                <option>male</option>
                <option>female</option>
            </options>
        </enum>
        <int min="6" max="80">
            <cols>
                <col>age</col>
            </cols>
        </int>
    </col-families>
</table>
